services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-web
    image: vovan4eg/web:1
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./web_nginx.conf:/etc/nginx/conf.d/default.conf

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-api
    image: vovan4eg/api:1
    container_name: api
    ports:
      - 5000:5000
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

